# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: InfoSec-SecurityResults
- group: 1CDN-SDF-Secrets
- group: 1CDN-Prod-Secrets

trigger:
  branches:
    include:
      - '2.0-preview'
      - 'release*'
  tags:
    include:
      - 'v*'

pool:
  vmImage: 'windows-latest'

steps:
  - task: YarnInstaller@3
    inputs:
      versionSpec: '1.x'
    displayName: 'Yarn 1.x'

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: GitHubComment@0
    inputs:
      gitHubConnection: 'ISS (3)'
      repositoryName: '$(Build.Repository.Name)'
      id: '$(System.PullRequest.PullRequestNumber)'
      comment: 'Test message'
    displayName: 'Post bundle analysis result as PR comment in github'
